version: "2"
services:
  #
  #
  #
  ava:
    build:
      context: ./ava
    ports:
      - "0.0.0.0:9650:9650"
    entrypoint:
      - "/root/run.sh"
      - "${AVAX_USERNAME}"
      - "${AVAX_PASSWORD}"
      - "${AVAX_PK}"
      - "${AVAX_ADDRESS}"
      - "${C_AVAX_PK}"
      - "${C_AVAX_HEX_ADDRESS}"
      - "${C_AVAX_BECH32_ADDRESS}"

  #
  # Acala
  #
  acala:
    build:
      context: ./acala
    ports:
      - "0.0.0.0:9933:9933"
      - "0.0.0.0:9944:9944"
    entrypoint:
      - "./root/run.sh"
      - "${ACALA_ADDRESS}"

  #
  # Binance Smart Chain
  #
  binance:
    build:
      context: ./binance
    ports:
      - "0.0.0.0:8575:8575"
    entrypoint:
      - "./root/run.sh"
      - "${BINANCE_MNEMONIC}"
      - "${BINANCE_ADDRESS}"

  #
  # Bitcoin
  #
  bitcoin:
    build:
      context: ./bitcoin
    ports:
      - "0.0.0.0:18443:18443"
    entrypoint:
      - "./root/run.sh"
      - "${BITCOIN_ADDRESS}"
      - "${BITCOIN_PK}"

  #
  # Bitcoin Cash
  #
  bitcoincash:
    build:
      context: ./bitcoincash
    ports:
      - "0.0.0.0:19443:19443"
    entrypoint:
      - "./root/run.sh"
      - "${BITCOINCASH_ADDRESS}"

  #
  # DigiByte
  #
  digibyte:
    build:
      context: ./digibyte
    ports:
      - "0.0.0.0:20443:18443"
    entrypoint:
      - "/root/run.sh"
      - "${DIGIBYTE_ADDRESS}"

  #
  # Dogecoin
  #
  dogecoin:
    build:
      context: ./dogecoin
    ports:
      - "0.0.0.0:18332:18332"
    entrypoint:
      - "./root/run.sh"
      - "${DOGECOIN_ADDRESS}"

  #
  # Ethereum
  #
  ethereum:
    build:
      context: ./ethereum
    ports:
      - "0.0.0.0:8545:8545"
    entrypoint:
      - "./root/run.sh"
      - "${ETHEREUM_MNEMONIC}"
      - "${ETHEREUM_ADDRESS}"

  #
  # Fantom
  #
  fantom:
    build:
      context: ./fantom
    ports:
      - "0.0.0.0:18545:18545"
    entrypoint:
      - "./root/run.sh"
      - "${FANTOM_MNEMONIC}"
      - "${FANTOM_ADDRESS}"

  #
  # Filecoin
  #
  filecoin:
    build:
      context: ./filecoin
    ports:
      - "0.0.0.0:1234:1234"
    entrypoint:
      - "/root/run.sh"

  #
  # Solana
  #
  solana:
    build:
      context: ./solana
    ports:
      - "0.0.0.0:8899:8899"
      - "0.0.0.0:8900:8900"
      - "0.0.0.0:9900:9900"
    entrypoint:
      - "./root/run.sh"

  #
  # Zcash
  #
  zcash:
    build:
      context: ./zcash
    ports:
      - "0.0.0.0:18232:18232"
    entrypoint:
      - "./root/run.sh"
      - "${ZCASH_ADDRESS}"

  ##
  ## Terra
  ##
  terra:
    build:
      context: ./terra
    ports:
      - "0.0.0.0:26657:26657"
    entrypoint:
      - "./root/run.sh"
      - "${TERRA_ADDRESS}"
